#!/bin/bash
API_KEY=$(cat $HOME/.secret/openai.apikey)
prompt=$1
resp=$(curl --silent https://api.openai.com/v1/images/generations \
	-H "Content-Type: application/json" \
	-H "Authorization: Bearer $API_KEY" \
	-d "{\"prompt\": \"$prompt\", \"n\": 2, \"size\": \"512x512\"}")
echo "$resp" | tee result.txt | jq -r ".data[].url"
